### PR TITLE
ObjectTable: select all on current page only

### LINKED ISSUE #112: Select all toggle, selects ALL items in BC Box (including not visible items on other pages)
#### Describe the bug
When you toggle the "select all" radio button, it selects all the items on the BC Box bucket. Applying any action to this selection applies it to everything in the bucket.

ie. Deleting (a page of items) deletes all the items in the bucket

#### Expected behavior
Apply action to the selected items on the current page (not the entire bucket)
This would match the UX of other sites, as to not delete items that are not visible on the current page

### PR DESCRIPTION
**Pull request by norrisng-bc**
# Description

This PR resolves #112.

The "select all" checkbox in the objects table now only selects items visible on the current page.

Primevue doesn't provide a native way to do this at the moment (see primefaces/primevue/issues/3477), so the solution involved figuring out what objects are on the current page.

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3365

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have checked that unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

The DOM had to be directly queried as a workaround.

For the most part, the list of objects provided by `DataTable`'s `value-change` emit is correctly sorted, in that it matches what's currently displayed in the table.

However, this is _not_ the case on initial page load. Instead, `value-change` simply uses the order as returned by the COMS API (specifically, by `GET /object`); however, the `DataTable` default sort order (and therefore the display order on initial page load) is the last updated date, which differs from the order returned by the COMS API.

Since the updated "select all" behaviour works by selecting the top row plus the next `{number of items per page}` objects (both of these are available via the `on-page` emit), a discrepancy in object order will result in the "wrong" items being selected (i.e. some objects on the current page don't get selected, while others on other pages do).

As a workaround, a DOM query on the `DataTable` is used to determine the actual display order. This is made possible by adding a custom HTML attribute (`data-objectid`) containing the object ID in each table row.

### CODE REVIEW

File: frontend/src/components/object/ObjectTable.vue [hunk 1]
```diff
@@ -54,6 +54,39 @@ const tableData: Ref<Array<COMSObjectDataSource>> = ref([]);
...
+ * @function unselectAllObjects
+ * Helper function for unselecting all objects
+ */
+function unselectAllObjects() {
+  objectStore.setSelectedObjects([]);
+  selectAll.value = false;
+}
+
+/**
+ * @function queryTableOrder
```
Comment (TimCsaky) [inline frontend/src/components/object/ObjectTable.vue:80]: not sure about thew name of this function. maybe `selectAllVisible()`?

File: frontend/src/components/object/ObjectTable.vue [hunk 2]
```diff
@@ -175,7 +257,10 @@ const filters = ref({
         body-class="truncate"
       >
         <template #body="{ data }">
-          <div v-tooltip.bottom="{ value: data.name }">
+          <div
+            v-tooltip.bottom="{ value: data.name }"
+            :data-objectid="data.id"
```
Comment (TimCsaky) [inline frontend/src/components/object/ObjectTable.vue:262]: feels a bit precarious adding this attribute to the tooltip. maybe it should appear in a hidden column.
i wonder if it's also available from the dataKey for each row (https://primevue.org/datatable/#api.datatable.props.dataKey)

**Review by TimCsaky — COMMENTED** [review]
If we're going to get visible rows by inspecting the DOM maybe you dont need to look at first and page. just do 'data.filter(obj => domIds.includes(obj.id)'
just trying to make things easier.. not sure if it's as simple as that

File: frontend/src/components/object/ObjectTable.vue [hunk 3]
```diff
@@ -54,6 +54,39 @@ const tableData: Ref<Array<COMSObjectDataSource>> = ref([]);
...
+
+// list of objects, in the order dislpayed in the DataTable
+const objectsList: Ref<Array<COMSObject>> = ref([]);
+
+// Initial page load?
+const isInitialLoad = ref(true);
+
+// DataTable pagination state
+const itemsPerPage = ref(10);
+const currentPageTop = ref(0);
```
Comment (jujaga) [inline frontend/src/components/object/ObjectTable.vue:68]: Do we have these magic numbers as constants somewhere? I know we generally use 10 as our default pagination size, but that should be defined as a constant across the codebase so that we're not just raw-defining default integer states.

File: frontend/src/components/object/ObjectTable.vue [hunk 4]
```diff
@@ -111,13 +188,18 @@ const filters = ref({
...
       current-page-report-template="{first}-{last} of {totalRecords}"
       :rows-per-page-options="[10, 20, 50]"
       sort-field="lastUpdatedDate"
       :sort-order="-1"
       :global-filter-fields="['name']"
+      :select-all="selectAll"
+      @select-all-change="onSelectAllChange"
+      @page="onPage"
+      @value-change="onValueChange"
+      @sort="onSort"
```
Comment (jujaga) [inline frontend/src/components/object/ObjectTable.vue:202]: Style: Let's make sure the attributes are alphabetically sorted if possible.

File: frontend/src/components/object/ObjectTable.vue [hunk 5]
```diff
@@ -98,6 +131,50 @@ const filters = ref({
...
+  }
+};
+
+const onPage = (event: any) => {
+  currentPageTop.value = event.first;
+  itemsPerPage.value = event.rows;
+  unselectAllObjects();
+};
+
+const onValueChange = (event: any) => {
```
Comment (jujaga) [inline frontend/src/components/object/ObjectTable.vue:171]: Is there any way we can be more specific about the type of event that will be coming in? Sometimes the `any` keyword is necessary, but that is usually indicative of either a breakdown of typescript, or the actual data structure expectations haven't been thoroughly investigated yet.

File: frontend/src/components/object/ObjectTable.vue [hunk 6]
```diff
@@ -98,6 +131,50 @@ const filters = ref({
...
 });
+
+const onSelectAllChange = (event: any) => {
+  selectAll.value = event.checked;
+  if (event.checked) {
+    if (isInitialLoad.value) {
+      /*
+       * On initial page load, the object order returned by this emit doesn't corespond
+       * to the actual display order - it's just the order returned by the COMS API.
+       * Workaround: directly query the DOM to figure out the actual display order (see queryTableOrder()).
```
Comment (jujaga) [inline frontend/src/components/object/ObjectTable.vue:142]: Isn't it the datatable component's job to be managing the order? I'm not completely sure why we need to be doing this, unless we need the explicit data ordering value in this parent component and there isn't any other way to pull that information from the datatable API?

File: frontend/src/components/object/ObjectTable.vue (hunk 3 above)
Comment (norrisng-bc) [reply frontend/src/components/object/ObjectTable.vue:68]: It was previously a magic number as well, as `<DataTable :rows:"10">`. There's `:rows-per-page-options="[10, 20, 50]"` but otherwise that's it afaik.

File: frontend/src/components/object/ObjectTable.vue (hunk 6 above)
Comment (norrisng-bc) [reply frontend/src/components/object/ObjectTable.vue:142]: Initial page load is an edge case - typically, the event returned by the `value-change` emit is in sorted order, but only on page load does it return the order from the COMS API instead of what's displayed. If you paginate, change sort order etc after this initial load it'll be in the correct order though.

**Review by kyle1morel — APPROVED** [review]

**Review by jujaga — APPROVED** [review]
